[package]
name = "ebpf-metrics"
version = "0.1.0"
description = "eBPF metrics emitter based on OpenMetrics standards"
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
